### ISSUE TITLE
Crash when setting B:wrench=false

### ISSUE THREAD

**Issue by OrdinatorStouff** [CyclopsMC/CommonCapabilities#11]
Discovered when trying to disable wrench as instructed [here](https://github.com/CyclopsMC/CyclopsCore/issues/77#issuecomment-333338675) that the server would crash on startup.

[Crashlog](https://gist.github.com/OrdinatorStouff/6406ae4120df47ddb705439d31d4d8c0)

**Comment by rubensworks** [comment]
Ah yes, my bad, that capability is required by Integrated Dynamics, so you won't be able to disable it.

Unless you disable the ID wrench itself as well, but this would hinder gameplay...
