### ISSUE TITLE
TE Satchel + IItemHandler Mod Incompatibilities

### ISSUE THREAD

**Issue by MaxNeedsSnacks** [CyclopsMC/CommonCapabilities#20]
#### Issue type:

- 🐛 Bug / ❓ Question(?)

____

#### Short description:

(Related issues: Direwolf20-MC/BuildingGadgets#280, Direwolf20-MC/BuildingGadgets#289, NillerMedDild/Enigmatica2Expert#1138)

Recently, a couple of users have recently reported a problem happening with the mod interaction between Thermal Expansion and other mods such as Dire's Building Gadgets or Better Builder's Wands. The problem ended up being closed as unresolved on the Building Gadgets tracker, but we whittled it down to there being *some* mod that interferes with Satchels and adds Item Handler Capabilities to them where there were none originally.

I went through all the mods in the pack (Enigmatica2Expert v1.62) and the only one I could really find which modified TE satchels at all was Common Capabilities. Now I'm not sure whether the issue actually lies with your mod in this case, but if not, I'm pretty sure I could just disable the Satchel capability in your mod's config and be done with it (most likely), but if this actually is a bug that can be fixed, I just wanted to let you know ^^

#### Steps to reproduce the problem:

> I crash when I equip the building gadget, only fix is to not use it or get rid of the mod. Ironically, I get the same crash with builders wand.
[...]
E2E modpack. I wasn't always having issues with it, I successfully used it for an entire schematic copy and paste, as well as tons of building-to-me and plane block placements before this.

from https://github.com/Direwolf20-MC/BuildingGadgets/issues/289#issue-435759112

#### Expected behaviour:

The client should crash producing a log similar to [this](https://github.com/Endlessgem/Crashreports/blob/master/crash-2019-04-22_14.35.54-client.txt)

____

#### Versions:

- This mod: 2.2.0
- Minecraft: 1.12.2
- Forge: 2781

**Comment by rubensworks** [comment]
I'll look into it asap, thanks for reporting!

**Comment by rubensworks** [comment]
(I'll give this a higher priority)

**Comment by rubensworks** [comment]
Pushed a fixed release (2.2.1) to CurseForge, also requires a CyclopsCore update.

For reference, all mod compacts can be disabled separately using the CommonCaps config file, just in case similar problems would arise in the future.

**Comment by MaxNeedsSnacks** [comment]
Awesome, thanks!
