### ISSUE TITLE
Crash when using an Integrated Terminals Terminal to Craft an Integrated Tunnels Energy Interface.

### ISSUE THREAD

**Issue by VT-14** [CyclopsMC/CommonCapabilities#21]
#### Issue type:

- :bug: Bug

____

#### Short description:

So far, a one-time crash while using the Integrated Terminals Terminal.  NullPointerException on Updating screen events, with Common Capabilities being the top of the stack trace.

#### Steps to reproduce the problem:

I have not reproduced this crash yet.  I had been using the Terminal for several hours by this point.  I was on the DevCraft4 sever.  What I think I was trying to craft an Integrated Tunnels Energy Interface from an Integrated Terminals Terminal.  I would have crafted the redstone block and used the terminal to send it to storage, then crafted an Energy Battery and put it in storage using the terminal.  Attempting to craft the Energy Interface caused my game to freeze for ~10 seconds and finally crash.

When I logged in and attempted crafting the Energy Interface again, only 1 Menril Chunk (middle left) got moved for the recipe.  I crafted one set manually without any issues (no more Energy Batteries in storage).

#### Expected behaviour:

No Crash.

____

#### Versions:

DevCraft4 1.0.1
- This mod: 2.2.1 (CommonCapabilities)
- Minecraft: 1.12.2
- Forge: 14.23.5.2836

- Integrated Dynamics: 1.0.11
- Integrated Terminals: 1.0.6
- Integrated Tunnels: 1.6.8
- Just Enough Items: 4.15.0.278 

#### Log file:

https://gist.github.com/VT-14/f351026186988e15d2e5de08bd803ff6

**Comment by rubensworks** [comment]
Thanks for reporting, but this has already been fixed in https://github.com/CyclopsMC/CommonCapabilitiesAPI/commit/69b5e5172427cbbac516b61bd9fdb49e28f81d16.
Will make a new release soon.
