### ISSUE TITLE
Potential Colossal Chests incompatibility

### ISSUE THREAD

**Issue by g-rock84** [CyclopsMC/CommonCapabilities#22]
First off, thank you so much for such awesome mods! I have fallen head over heals with all the Integrated mods and really appreciate your hard work so it hurts to report a bug... :( I am especially excited about the new terminals and autocrafting capabilities! I really want to make the the Refined Storage/AE2 replacement for me. I REALLY hope the bug is on my end or another mod that I can remove or update.

#### Issue type:

- :bug: When importing items into a Colossal Chest via the item importer the game crashes. When inputting items into the Colossal Chest via the Storage Terminal throws a CommonCapabilities error message in game.

____

#### Short description:

- When attempting to import items in a Colossal Chest via the item importer the game crashes. I attach the item interface to the Colossal Chest, then a logic cable and then an item importer to a vanilla chest with any number of items or item stacks (I tried one cobblestone, five iron ingots and a stack of 32 coal) and as soon as I add a boolean (true) variable to the "import all items" option slot the game crashes. 

- A similar thing happens when try to add or remove items from the Storage Terminal. It doesn't matter if I manually add the items to the Colossal Chest first and then try to take them out via the Storage terminal or try to add them. CommonCapabilities throws an error but the game does crash, The items either don't get extracted (if they were already in the chest) or they get kicked out of the players inventory on to the ground.

#### Steps to reproduce the problem:

Item Importer:
1. Attach item interface to Colossal Chest.

2. Attach logic cable to item interface.

3. Attach item importer to vanilla chest.

4. Add Boolean true variable to the item importer "import all items" slot.

Storage Terminal:
1. Attach item interface to Colossal Chest.

2. Attach logic cable to item interface,

3. Attach Storage Terminal to logic cable.

4. Try to drop an item into the chest inventory.

OR

4. Add and item to the chest manually.

5. Try to remove item from chest via the Storage Terminal.

#### Expected behaviour:

- What I was expecting was that the items would get pulled out of the vanilla chest via the item importer and deposited into the Colossal Chest.

- I was also expecting to be able to add and remove items from the Colossal Chest from the Storage Terminal.

____

#### Versions:

- This mod: 2.3.0 & 2.4.1 (tested on both)
- Minecraft: 1.12.2
- Forge: 14.23.5.2836

#### Log file:

https://paste.dimdev.org/yicifabeno.mccrash

**Comment by rubensworks** [comment]
Thanks for reporting this, but you seem to be using outdated mods.
You need Common Capabilities of 2.4.0 or higher, and ColossalChests 1.7.2 or higher.

Please let me know if it still does not work after updating.

**Comment by g-rock84** [comment]
Yep you're right. Rule #1: make sure your mods are updated... I wasn't aware that colossal chests had been updated recently. I updated to 1.7.2 and that fixed the issues. Thank you for your time! Sorry about that.
