### ISSUE TITLE
is this one on you?

### ISSUE THREAD

**Issue by border999** [CyclopsMC/CommonCapabilities#23]
https://gist.github.com/border999/0ff48ff222cac6f22350c6329e6b2505

**Comment by border999** [comment]
https://github.com/Davoleo/Metallurgy-4-Reforged/issues/178

**Comment by rubensworks** [comment]
Why do you think CommonCapabilities has anything to do with this? I don't see it mentioned in the crashlog.

**Comment by border999** [comment]
https://gist.github.com/border999/c08eea866f3cbb9c40b72f5483c3fda7
here's the full log

<blockquote><img src="https://avatars2.githubusercontent.com/u/11824584?s=400&v=4" width="48" align="right"><div><img src="https://github.githubassets.com/favicon.ico" height="14"> Gist</div><div><strong><a href="https://gist.github.com/border999/c08eea866f3cbb9c40b72f5483c3fda7">latest.log</a></strong></div><div>GitHub Gist: instantly share code, notes, and snippets.</div></blockquote>

**Comment by rubensworks** [comment]
Still does not seem related to this mod.
