### ISSUE TITLE
Evilcraft crash

### ISSUE THREAD

**Issue by sossololpipi** [CyclopsMC/CommonCapabilities#24]
#### Issue type:

- :bug: Bug

____

#### Short description:

Launch the game with the most updated current version of the mod

Download the two mods and launch the game with them

#### Expected behaviour:

The game to launch normally

____

#### Versions:

2.4.4

- This mod: Common Capabilities
- Minecraft: Forge
- Forge:  14.23.5.2784

#### Log file:

[log.txt](https://github.com/CyclopsMC/CommonCapabilities/files/3428621/log.txt)

**Comment by rubensworks** [comment]
That's a weird crash. Could you try reproducing with just the offending mods installed? I suspect that some other (core)mod is causing trouble.

**Comment by sossololpipi** [comment]
> That's a weird crash. Could you try reproducing with just the offending mods installed? I suspect that some other (core)mod is causing trouble.

Upon reverting the mod's version (because I updated it) , the game still crashes for the same reason.

**Comment by rubensworks** [comment]
Any chance you changed the config file?
