### ISSUE TITLE
Crash with latest versions of Common Capabilities and Botania

### ISSUE THREAD

**Issue by Luckyday84** [CyclopsMC/CommonCapabilities#25]
#### Issue type: Crash On startrup with Botania

- :bug: Bug

____

#### Short description:

Game will crash on start up

#### Steps to reproduce the problem:

Down grading everything Integrated Dynamics related fixes the crash

1. ...

____

#### Versions:

2.4.6

- This mod: common capabilities and botania
- Minecraft: 1.12.2
- Forge: 2847

#### Log file:

https://paste.dimdev.org/erijefedow.mccrash

**Comment by rubensworks** [comment]
Just tried this myself, and everything seems to be working properly here.
Some other mod is probably messing with things.
Have you tried without any ID-related mods and Botania?

Also, this mod is never mentioned in the crashlog, which seems to indicate that this mod has nothing to do with this.

**Comment by Luckyday84** [comment]
Sorry you're correct after I did more testing I can't seem to make this happen again testing on a smaller mod pack.  Its definitely an issue with 3 or so mods I have in the pack.

**Comment by MokahTGS** [comment]
We reproduced a similar crash:

https://paste.dimdev.org/emabisacoh.mccrash

Full Mod List: https://pastebin.com/dEgt8NYw

Forge 2847

<blockquote><div><strong><a href="https://paste.dimdev.org/emabisacoh.mccrash">hastebin</a></strong></div></blockquote>
<blockquote><img src="https://pastebin.com/i/facebook.png" width="48" align="right"><div>Pastebin</div><div><strong><a href="https://pastebin.com/dEgt8NYw">1.12.2  AbyssalCraft Integration-1.12.2-1.10.0.jar  AbyssalCraft-1.12.2-1.9.18.j - Pastebin.com</a></strong></div></blockquote>

**Comment by rubensworks** [comment]
@MokahTGS As mentioned before in this issue, I see no reason in your crashlog why this mod could be causing your crash.
