### ISSUE TITLE
1.12.2 Client Crash on Start

### ISSUE THREAD

**Issue by MokahTGS** [CyclopsMC/CommonCapabilities#26]
We reproduced a similar crash:

https://paste.dimdev.org/emabisacoh.mccrash

Full Mod List: https://pastebin.com/dEgt8NYw

#### Issue type:

- :bug: Bug

#### Short description:

Getting a Client crash on load with newest and rolled back versions of Common Capabilities along with Botania.  Rolling back all thing Integrated Dyn did not stop the crash.  

#### Versions:

- This mod: CommonCapabilities-1.12.2-2.4.6.jar
- Minecraft: 1.12.2
- Forge: Forge 2847

**Comment by rubensworks** [comment]
Duplicate of #25.
