### ISSUE TITLE
Random crash when requesting items to be crafted

### ISSUE THREAD

**Issue by Kurtchekov** [CyclopsMC/CommonCapabilities#27]
#### Issue type:

- :bug: Bug

____

#### Short description:

Sometimes, when requesting Integrated Crafting to craft several items from the Storage Terminal, the game crashes.

#### Steps to reproduce the problem:

1. Make a network with crafters and item interfaces, which only interacts with crates from Immersive Engineering and Metal Crates from "Barrels, Drums, Storage & More" mods.
2. Request a certain item to be crafted. Sometimes it will craft just fine, sometimes it will crash the game.

#### Versions:

- This mod: 2.4.6
- Minecraft: 1.12.2
- Forge: 14.23.5.2847

#### Log file:

https://pastebin.com/KucAYkqg

**Comment by rubensworks** [comment]
Thanks for reporting!

**Comment by rubensworks** [comment]
This _should_ be fixed in ID 1.1.7 (I see you are using 1.1.6). Feel free to re-open this issue should this not be the case.
