### ISSUE TITLE
Can The CurseForge Page be Updated?

### ISSUE THREAD

**Issue by AbsorbingSafe11** [CyclopsMC/CommonCapabilities#28]
#### Issue type:

- The CurseForge mod page for Common Capabilities may list outdated information.

____

#### Question:

- Can the mod page on CurseForge be updated to show how it works in newer versions and the older description be hidden for users of older versions?
- Alternatively, can the latest version to support a feature be listed near the features' explanations?
- Not a question, but great work on all of your mods. (thank you very much for updating to 1.16.4)

**Comment by rubensworks** [comment]
Done :-)
