### ISSUE TITLE
ComputerCRaft / CC:Tweaked Support

### ISSUE THREAD

**Issue by mcenderdragon** [CyclopsMC/CommonCapabilities#30]
ComputerCRaft as generic Peripherals which can be used to acess Capabiltiy Method from the Lua code. It would be awesome if such compatibility was added. (can be done with soft dependencies wuite easily)

**Comment by rubensworks** [comment]
I'm not sure what you have in mind exactly, could you clarify?

**Comment by mcenderdragon** [comment]
expose all capabilities to the computer craft api using generic capabilities, like [FluidMethods](https://github.com/cc-tweaked/CC-Tweaked/blob/9d50d6414ce84ed2b442c933ca2fb60c97849c6b/src/main/java/dan200/computercraft/shared/peripheral/generic/methods/FluidMethods.java) or [EnergyMethods](https://github.com/cc-tweaked/CC-Tweaked/blob/9d50d6414ce84ed2b442c933ca2fb60c97849c6b/src/main/java/dan200/computercraft/shared/peripheral/generic/methods/EnergyMethods.java). This way temperatur or "work" could be queried of all supported machines using computers.

**Comment by rubensworks** [comment]
I like that idea, but I'm afraid that this is not really in-scope for this mod (since it only targets adding new capabilities).
Perhaps you can open an issue within the CC issue tracker to request the feature there?
