### ISSUE TITLE
crash with latest ver(neoforge 1.21.1 .89)

### ISSUE THREAD

**Issue by VaporeonScripts** [CyclopsMC/CommonCapabilities#35]
#### Issue type:

- :bug: Bug

____

#### Short description:

crash on boot

#### Steps to reproduce the problem:

use latest common capabilities version

#### Expected behaviour:

normal loading

____

#### Versions:

- This mod: commoncapabilities-1.21.1-neoforge-2.9.7-180
- Minecraft: 1.21.1
- Mod loader version: neoforge 1.21.1 21.1.89

#### Log file:
https://mclo.gs/66ynwUh

**Comment by rubensworks** [comment]
@VaporeonScripts Your issue appears to be not following one of the allowed issue templates, which breaks our automation tools. Please update your issue to the proper template.

**Comment by Jack-McKalling** [comment]
Please use the bug report template provided when using the "New Issue" button.
We need more information than just a crashlog link, and the template shows you which.

Glancing at the log, I can't see anything specific happening without further info.
I do notice that you're using the beta release for both Common Capabilities and EvilCraft.
If anything, I'd like to know what happens for the latest full release for both.

**Comment by VaporeonScripts** [comment]
adjusted
