### ISSUE TITLE
Crash with IC2

### ISSUE THREAD

**Issue by jasonsaffle13** [CyclopsMC/CommonCapabilities#5]
IC2 build 167 forward crashes with cyclops core any current build as of 1.9.4
when running Minecraft version 1.10.2 This is with Forge 12.18.3.2239 I have not
tried with other versions of Forge.

http://paste.ubuntu.com/24287866/

It's a bug in CommonCapabilities, in build 167 the chunk loader changed from
extending TileEntityElectricMachine to extending TileEntityInventory, which
because CommonCapabilities is expecting TileEntityElectricMachine means it
crashes.

**Comment by rubensworks** [comment]
@jasonsaffle13 I won't be able to fix this issue soon, so you'd best disable the IC2 modcompat from the CommonCapabilities config file.

**Comment by 0Navis0** [comment]
I get the same crash https://pastebin.com/TdM00CiX

**Comment by jasonsaffle13** [comment]
Then use Same work around.
