### ISSUE TITLE
broken IndustrialCraft compatibility

### ISSUE THREAD

**Issue by 0Navis0** [CyclopsMC/CommonCapabilities#6]
The 2.7.33 IndustrialCraft version causes CommonCompability to crash. https://pastebin.com/yBB8AyW4

**Comment by rubensworks** [comment]
You may want to report this to the IC2 developers as well.
This part of the crashlog looks suspicious:
```
Caused by: java.lang.NullPointerException
    at ic2.core.util.ConfigUtil.getBool(ConfigUtil.java:83)
    at ic2.core.item.tool.ItemToolWrench.<clinit>(ItemToolWrench.java:200)
```

**Comment by 0Navis0** [comment]
http://bt.industrial-craft.net/view.php?id=2182

**Comment by Chocohead** [comment]
The crash is from loading before IC2, so the config hasn't generated properly yet. Which means when the wrench tries to get a value from the config, it's not initialised properly, so ends up trying to get the property from a null section.

`after:IC2` in the `@Mod`  dependencies should be enough to ensure it loads properly.

**Comment by rubensworks** [comment]
I'll look into adding this in the next update.

**Comment by TheLimePixel** [comment]
Which I'm hoping will be soon.

**Comment by rubensworks** [comment]
Fix will be included in next release.

**Comment by TheLimePixel** [comment]
Great! All I want is to just be able to use Integrated Dynamics with IC2 again as soon as possible

**Comment by rubensworks** [comment]
@EmosewaGamer Several things you can do in the meantime:
* Use a ComCap dev build
* Downgrade IC2
* Disable IC2 compat in ComCap.
