### ISSUE TITLE
Crash with ic2

### ISSUE THREAD

**Issue by IchigoGames** [CyclopsMC/CommonCapabilities#7]
I updated ic2 and i have your mod but when i updated ic2 your mod crashed game on load heres the crash report

Minecraft 1.11.2
Forge 2298
CommonCapabilities-1.11.2-1.3.2
industrialcraft-2-2.7.33-ex111

https://pastebin.com/YRqs1suc

**Comment by IchigoGames** [comment]
side note it looks like if i use CommonCapabilities-1.11.2-1.3.1 with new ic2 it does not crash.

**Comment by rubensworks** [comment]
Duplicate of #6
